[package]
name = "actix-request-identifier"
version = "0.1.0"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
futures = "0.3.4"
uuid = { version = "0.8.1", default-features = false, features = [ "v4", "serde" ] }
